name: RandomCoords
main: me.carl230690.RandomCoords.RandomCoords.Main
version: 1.0
website: http://www.doragoncraft.com/
author: carl230690
description: >
              Random Teleport On sign click
commands:
    rc:
        description: Teleport To Random Coordinate
        aliases: [randomcoordinate]
